mytestkey=This value is from LOCAL properties file

merchant.username=merchant_username
merchant.password=merchant_password
notification.url=http://localhost:8083/v1/trustly/notification
trustly.deposit.url=http://localhost:8084/payment/initiate
processing.notification.url=http://localhost:8082/payments/notification