mytestkey=This value is from PROD properties file

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

trustlyprovider.deposit.url=${TRUSTLY_DEPOSIT_URL}